namespace DLA.Models.TownHallModels;
public class ElixirTownHall {
    public int Barbarian { get; set; } = 0;
    public int Archer { get; set; } = 0;
    public int Giant { get; set; } = 0;
    public int Goblin { get; set; } = 0;
    public int WallBreaker { get; set; } = 0;
    public int Balloon { get; set; } = 0;
    public int Wizard { get; set; } = 0;
    public int Healer { get; set; } = 0;
    public int Dragon { get; set; } = 0;
    public int PEKKA { get; set; } = 0;
    public int BabyDragon { get; set; } = 0;
    public int Miner { get; set; } = 0;
    public int ElectroDragon { get; set; } = 0;
    public int Yeti { get; set; } = 0;
    public int DragonRider { get; set; } = 0;
    public int ElectroTitan { get; set; } = 0;
    public int RootRider { get; set; } = 0;
    public int Thrower { get; set; } = 0;
    public int LightningSpell { get; set; } = 0;
    public int HealingSpell { get; set; } = 0;
    public int RageSpell { get; set; } = 0;
    public int JumpSpell { get; set; } = 0;
    public int FreezeSpell { get; set; } = 0;
    public int CloneSpell { get; set; } = 0;
    public int InvisibilitySpell { get; set; } = 0;
    public int RecallSpell { get; set; } = 0;
    public int ReviveSpell { get; set; } = 0;
}
